version: '3.5'

services:
  postgres:
    container_name: clair_postgres
    image: postgres:latest
    ports:
      - "5432:5454"
    environment:
      POSTGRES_PASSWORD: ""
    networks:
      mynetwork:
        aliases:
          - postgres.internal.example.com


  clair:
    container_name: clair_clair
    restart: on-failure
    image: quay.io/coreos/clair:latest
    ports:
      - "6060:6060"
      - "6061:6061"
    depends_on:
      - postgres
    volumes:
      - ./tmp:/tmp
      - ./clair_config:/config
    command: [-config, /config/config.yaml]
    networks:
      mynetwork:
        aliases:
          - clair.internal.example.com

  registry:
    image: registry:latest
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
    networks:
      mynetwork:
        aliases:
          - registry.internal.example.com

networks:
  mynetwork:
#    driver: bridge
    name: mynetwork